# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00b3a41fd0b48f71186a3c76ae773ae627b5a02c70e4794e42e1aac5bcaaae2651f63a13d6c9c5f00b609a8bbd5ed83451892474d6a033df325f31e28321d85a

test:
  secret_key_base: 4b163f8dc5edcfb2e4109dfa80011d12a02407434189a7fbe74a6b4d49370dc13591c38ab4a3fd77643638fc89c11175c9ec2e19c742bea99ea0279cf067e95c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
